name: Backend CI (lint & tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest

    - name: Run flake8
      run: |
        if [ ! -f .flake8 ]; then cat > .flake8 <<'EOF'
[flake8]
max-line-length = 100
exclude = .git,__pycache__,migrations,venv
EOF
        fi
        flake8 .

    - name: Run pytest
      run: pytest -q
